### ISSUE TITLE
add simple css support

### ISSUE THREAD

**Issue by MarcLoupias** [MarcLoupias/mdfc-map-to-html#5]
## custom css

**What:** The user could just want to inject a custom stylesheet in each html file. 

**How:** Just need a stylesheet import in that case, then the user style his html from tags as selectors only without any css class.

## ready to use css solutions

**What:** The user could want to inject a css from a generic solution like : 
- [jgthms/wysiwyg.css](https://github.com/jgthms/wysiwyg.css)
- [sindresorhus/github-markdown-css](https://github.com/sindresorhus/github-markdown-css)
- ???

**How:** In that case the user needs to define : 
- a container tag (`<div>` or `<article>`)
- a class name on that import
- stylesheet import

#### anchor and title management

See #8 

#### code highlighting

See #9 

## impl solution

Using front-matter data in [`map-parsed-document.ts`](https://github.com/MarcLoupias/mdfc-map-to-html/blob/develop/src/map-parsed-document.ts) could be the easiest way to achieve that.

Test [the data structure here](http://nodeca.github.io/js-yaml/).

```yaml
---
htmlHead:
    title: 'uber title for uber document'
    links:
        - href: mobile.css
          rel: stylesheet
          media: all
        - href: print.css
          rel: stylesheet
          media: print
        - href: desktop.css
          rel: stylesheet
          media: 'screen and (min-width: 600px)'
        - href: favicon32.png
          rel: icon
        - href: favicon72.png
          rel: apple-touch-icon-precomposed
          sizes: 72x72
    metaTags:
        - name: description
          content: 'my uber document'
        - name: viewport
          content: 'width=device-width, initial-scale=1, minimal-ui'
        - property: 'og:type'
          content: website
        
---
```

The multiple `<link>` tags are wrapped into a `htmlHead` data to set a namespace to extends to others features (document title, meta tags for SEO, ...). 

See [HTML/Element/link from developer.mozilla.org](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link) for an exhaustive description of `<link>` tag.

Others features should be handled in a different PR.

See #6 for `<title>` support and #7 for `<meta>` support.
