### ISSUE TITLE
add meta tags support

### ISSUE THREAD

**Issue by MarcLoupias** [MarcLoupias/mdfc-map-to-html#7]
See #5 solution and extends it to support `<meta>` tags.

**Comment by MarcLoupias** [comment]
## impl solution

Using front-matter data in [`map-parsed-document.ts`](https://github.com/MarcLoupias/mdfc-map-to-html/blob/develop/src/map-parsed-document.ts) could be the easiest way to achieve that.

Test [the data structure here](http://nodeca.github.io/js-yaml/).

```yaml
---
htmlHead:
    metaTags:
        - name: description
          content: 'my uber document'
        - name: viewport
          content: 'width=device-width, initial-scale=1, minimal-ui'
        - property: 'og:type'
          content: website
        - httpEquiv: 'Expires'
          content: 0
---
```
[`<meta>` tags list](https://gist.github.com/lancejpollard/1978404 )

### charset

`<meta charset="utf-8">` is not supported. This tag is set by default in any case.
