### ISSUE TITLE
add code highlighting support

### ISSUE THREAD

**Issue by MarcLoupias** [MarcLoupias/mdfc-map-to-html#9]
See #5 and extends it.

There is some tweak to do regarding [this issue](https://github.com/sindresorhus/github-markdown-css/issues/51) and [how marked handle code highlighting](https://marked.js.org/#/USING_ADVANCED.md#highlight) with [highlightjs](https://highlightjs.org/).

**Comment by MarcLoupias** [comment]
It just needs to add `<script>` tag support. See [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script).

Combined with #5 we have everything need to support [highlightjs](https://highlightjs.org).

Basic usage [is really simple](https://highlightjs.org/usage/) : 

> The bare minimum for using highlight.js on a web page is linking to the library along with one of the styles and calling `initHighlightingOnLoad`:
> 
> ```html
> <link rel="stylesheet" href="/path/to/styles/default.css">
> <script src="/path/to/highlight.pack.js"></script>
> <script>hljs.initHighlightingOnLoad();</script>
> ```

**Comment by MarcLoupias** [comment]
`<script>` support with front-matter : 

```yaml
---
htmlHead:
    scripts:
        - src: 'my-script.js'
          async: true
        - src: 'http://cdn.domain.tld/dependency.js'
          defer: true
          crossorigin: 'anonymous'
        - text: 'document.title = "a new title";'
---
```

should output

```html
<script src="my-script.js" async></script>
<script src="http://cdn.domain.tld/dependency.js" defer></script>
<script>document.title = "a new title";</script>
```
